name: GitHub metrics
on:
  schedule:
      - cron: "0 0 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main", "develop"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # base metrics
      - name: base_metrics
        uses: lowlighter/metrics@latest
        with:
          filename: base_metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: D-xuanmo
          template: classic
          config_timezone: Asia/Shanghai
          base: "header, activity, community, repositories"
          plugin_traffic: yes
          plugin_lines: yes
