name: GitHub metrics
on:
  schedule:
      - cron: "0 0 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main", "develop"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # base metrics
      - name: base_metrics
        uses: lowlighter/metrics@latest
        with:
          filename: base_metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: D-xuanmo
          template: classic
          config_timezone: Asia/Shanghai
          base: "header, activity, community, repositories"
          plugin_traffic: yes
          plugin_lines: yes
      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "activity, repositories"
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
